platform :ios,'8.0'
#公有source pod 源
source 'https://github.com/CocoaPods/Specs.git'

target 'iOSLearning' do
pod 'JSONKit'
pod 'Reachability'
pod 'AFNetworking'
pod 'JSPatch'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'

end
